### ISSUE TITLE
[Bug]: Job endpoint returns a 500 when it should return an empty list

### ISSUE THREAD

**Issue by ryanhunter-jpl** [unity-sds/unity-sps-prototype#231] opened 2023-08-17 00:01 UTC
**Checked for duplicates**
Yes - I've already checked

**Describe the bug**
When using GET /{proc_id}:{procVersion}/jobs to get the list of jobs of a process that doesn't have any jobs - the WPS-T server responds with a 500 and the following stack trace.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/flask_ades_wpst/flask_ades_wpst/flask_wpst.py", line 92, in processes_jobs
    job_list = ades_base.get_jobs(procID)
  File "/flask_ades_wpst/flask_ades_wpst/ades_base.py", line 119, in get_jobs
    jobs_list = self._ades.get_jobs(proc_id)
  File "/flask_ades_wpst/flask_ades_wpst/ades_hysds.py", line 448, in get_jobs
    job_set = m.get_jobs()
  File "/otello/otello/mozart.py", line 128, in get_jobs
    raise Exception(req.text)
Exception: {"success": false, "message": "NotFoundError(404, 'index_not_found_exception', 'no such index [job_status-current]', job_status-current, index_or_alias)", "result": []}
```
**What did you expect?**
The endpoint should return a 200 with an empty list in the body.

**Reproducible steps**

1. Deploy a process
2. Send a GET request to /processes/{proc_id}:{proc_version}/jobs

**Comment by drewm-jpl** [comment] 2023-10-17 17:14
I'm unable to reproduce this bug, I'm seeing the expected behavior.

![image](https://github.com/unity-sds/unity-sps-prototype/assets/100967535/04cc481d-9af4-48b3-90c9-a23a37fd3167)

**Comment by LucaCinquini** [comment] 2023-10-31 13:47
Closing the ticket as possibly fixed by some other code changes.

**Closed by LucaCinquini** 2023-10-31 13:47 UTC
Labels: bug
